[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Informe Casillas"
authors = [{name = "Mastropierro", email = "mastropierro.francisco@gmail.com"}]
dynamic = ["version", "description"]